[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit TCS34725
    johnrickman/LiquidCrystal_I2C
    madhephaestus/ESP32Servo
